title = "A Rust Tutorial"
description = "Rust tutorial focused on type-theoretic and mathematical ideas"
base_url = "https://bhgomes.github.io/rust-tutorial"

build_search_index = true
compile_sass = true
generate_feed = false
ignored_content = []
minify_html = false

[markdown]
highlight_code = true
